### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-css-font-families#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://drab-flame.surge.sh/).

Did I do the font-face right?

**Comment by chrisvfritz** [comment]
That `@font-face` rule looks good! I do notice that you've copied and pasted some [text here](https://github.com/KatieMFritz/codelab-css-font-families/blob/master/style.css#L1-L5) though, creating some inconsistent indentation. Can you fix the indentation to conform to the two spaces that the rest of that file is using? :smiley:

**Comment by KatieMFritz** [comment]
Done.

**Comment by chrisvfritz** [comment]
:shipit:
